import { CableData, InstallationMethod, CableType, DeviceType } from './types';

// Data based on BS 7671 Tables
// 4D5 (Twin & Earth), 4D4A (PVC SWA), 4E4A (XLPE SWA)

export const CABLE_DATABASE: Record<CableType, CableData[]> = {
  [CableType.PVC_PVC]: [
    {
      size: 1,
      capacity: {
        [InstallationMethod.METHOD_A]: 10.5,
        [InstallationMethod.METHOD_B]: 13.5,
        [InstallationMethod.METHOD_C]: 16,
        [InstallationMethod.METHOD_D]: 18,
        [InstallationMethod.METHOD_E]: 17,
        [InstallationMethod.METHOD_F]: 18,
        [InstallationMethod.METHOD_G]: 19,
        [InstallationMethod.METHOD_100]: 13,
        [InstallationMethod.METHOD_101]: 10.5,
        [InstallationMethod.METHOD_102]: 13,
        [InstallationMethod.METHOD_103]: 8,
      },
      mvAm: 44,
    },
    {
      size: 1.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 13,
        [InstallationMethod.METHOD_B]: 17.5,
        [InstallationMethod.METHOD_C]: 20,
        [InstallationMethod.METHOD_D]: 22,
        [InstallationMethod.METHOD_E]: 22,
        [InstallationMethod.METHOD_F]: 23,
        [InstallationMethod.METHOD_G]: 24,
        [InstallationMethod.METHOD_100]: 16,
        [InstallationMethod.METHOD_101]: 13,
        [InstallationMethod.METHOD_102]: 16,
        [InstallationMethod.METHOD_103]: 10,
      },
      mvAm: 29,
    },
    {
      size: 2.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 18,
        [InstallationMethod.METHOD_B]: 24,
        [InstallationMethod.METHOD_C]: 27,
        [InstallationMethod.METHOD_D]: 30,
        [InstallationMethod.METHOD_E]: 30,
        [InstallationMethod.METHOD_F]: 31,
        [InstallationMethod.METHOD_G]: 33,
        [InstallationMethod.METHOD_100]: 21,
        [InstallationMethod.METHOD_101]: 18,
        [InstallationMethod.METHOD_102]: 21,
        [InstallationMethod.METHOD_103]: 13.5,
      },
      mvAm: 18,
    },
    {
      size: 4,
      capacity: {
        [InstallationMethod.METHOD_A]: 24,
        [InstallationMethod.METHOD_B]: 32,
        [InstallationMethod.METHOD_C]: 37,
        [InstallationMethod.METHOD_D]: 40,
        [InstallationMethod.METHOD_E]: 40,
        [InstallationMethod.METHOD_F]: 42,
        [InstallationMethod.METHOD_G]: 45,
        [InstallationMethod.METHOD_100]: 27,
        [InstallationMethod.METHOD_101]: 24,
        [InstallationMethod.METHOD_102]: 27,
        [InstallationMethod.METHOD_103]: 17.5,
      },
      mvAm: 11,
    },
    {
      size: 6,
      capacity: {
        [InstallationMethod.METHOD_A]: 31,
        [InstallationMethod.METHOD_B]: 41,
        [InstallationMethod.METHOD_C]: 47,
        [InstallationMethod.METHOD_D]: 51,
        [InstallationMethod.METHOD_E]: 51,
        [InstallationMethod.METHOD_F]: 54,
        [InstallationMethod.METHOD_G]: 58,
        [InstallationMethod.METHOD_100]: 34,
        [InstallationMethod.METHOD_101]: 31,
        [InstallationMethod.METHOD_102]: 35,
        [InstallationMethod.METHOD_103]: 23.5,
      },
      mvAm: 7.3,
    },
    {
      size: 10,
      capacity: {
        [InstallationMethod.METHOD_A]: 42,
        [InstallationMethod.METHOD_B]: 57,
        [InstallationMethod.METHOD_C]: 64,
        [InstallationMethod.METHOD_D]: 70,
        [InstallationMethod.METHOD_E]: 70,
        [InstallationMethod.METHOD_F]: 75,
        [InstallationMethod.METHOD_G]: 80,
        [InstallationMethod.METHOD_100]: 45,
        [InstallationMethod.METHOD_101]: 42,
        [InstallationMethod.METHOD_102]: 47,
        [InstallationMethod.METHOD_103]: 32,
      },
      mvAm: 4.4,
    },
    {
      size: 16,
      capacity: {
        [InstallationMethod.METHOD_A]: 56,
        [InstallationMethod.METHOD_B]: 76,
        [InstallationMethod.METHOD_C]: 85,
        [InstallationMethod.METHOD_D]: 94,
        [InstallationMethod.METHOD_E]: 94,
        [InstallationMethod.METHOD_F]: 100,
        [InstallationMethod.METHOD_G]: 107,
        [InstallationMethod.METHOD_100]: 62,
        [InstallationMethod.METHOD_101]: 56,
        [InstallationMethod.METHOD_102]: 63,
        [InstallationMethod.METHOD_103]: 42.5,
      },
      mvAm: 2.8,
    },
  ],
  [CableType.PVC_SWA]: [
    {
      size: 1.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 15,
        [InstallationMethod.METHOD_B]: 18,
        [InstallationMethod.METHOD_C]: 21,
        [InstallationMethod.METHOD_D]: 22,
        [InstallationMethod.METHOD_E]: 22,
        [InstallationMethod.METHOD_F]: 23,
        [InstallationMethod.METHOD_G]: 24,
        [InstallationMethod.METHOD_100]: 16,
        [InstallationMethod.METHOD_101]: 15,
        [InstallationMethod.METHOD_102]: 16,
        [InstallationMethod.METHOD_103]: 10,
      },
      mvAm: 29,
    },
    {
      size: 2.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 20,
        [InstallationMethod.METHOD_B]: 24,
        [InstallationMethod.METHOD_C]: 28,
        [InstallationMethod.METHOD_D]: 30,
        [InstallationMethod.METHOD_E]: 30,
        [InstallationMethod.METHOD_F]: 31,
        [InstallationMethod.METHOD_G]: 33,
        [InstallationMethod.METHOD_100]: 21,
        [InstallationMethod.METHOD_101]: 20,
        [InstallationMethod.METHOD_102]: 21,
        [InstallationMethod.METHOD_103]: 13.5,
      },
      mvAm: 18,
    },
    {
      size: 4,
      capacity: {
        [InstallationMethod.METHOD_A]: 27,
        [InstallationMethod.METHOD_B]: 32,
        [InstallationMethod.METHOD_C]: 38,
        [InstallationMethod.METHOD_D]: 40,
        [InstallationMethod.METHOD_E]: 40,
        [InstallationMethod.METHOD_F]: 42,
        [InstallationMethod.METHOD_G]: 45,
        [InstallationMethod.METHOD_100]: 27,
        [InstallationMethod.METHOD_101]: 27,
        [InstallationMethod.METHOD_102]: 27,
        [InstallationMethod.METHOD_103]: 17.5,
      },
      mvAm: 11,
    },
    {
      size: 6,
      capacity: {
        [InstallationMethod.METHOD_A]: 35,
        [InstallationMethod.METHOD_B]: 41,
        [InstallationMethod.METHOD_C]: 49,
        [InstallationMethod.METHOD_D]: 51,
        [InstallationMethod.METHOD_E]: 52,
        [InstallationMethod.METHOD_F]: 54,
        [InstallationMethod.METHOD_G]: 58,
        [InstallationMethod.METHOD_100]: 34,
        [InstallationMethod.METHOD_101]: 35,
        [InstallationMethod.METHOD_102]: 35,
        [InstallationMethod.METHOD_103]: 23.5,
      },
      mvAm: 7.3,
    },
    {
      size: 10,
      capacity: {
        [InstallationMethod.METHOD_A]: 48,
        [InstallationMethod.METHOD_B]: 57,
        [InstallationMethod.METHOD_C]: 67,
        [InstallationMethod.METHOD_D]: 70,
        [InstallationMethod.METHOD_E]: 71,
        [InstallationMethod.METHOD_F]: 75,
        [InstallationMethod.METHOD_G]: 80,
        [InstallationMethod.METHOD_100]: 45,
        [InstallationMethod.METHOD_101]: 48,
        [InstallationMethod.METHOD_102]: 47,
        [InstallationMethod.METHOD_103]: 32,
      },
      mvAm: 4.4,
    },
    {
      size: 16,
      capacity: {
        [InstallationMethod.METHOD_A]: 64,
        [InstallationMethod.METHOD_B]: 76,
        [InstallationMethod.METHOD_C]: 89,
        [InstallationMethod.METHOD_D]: 94,
        [InstallationMethod.METHOD_E]: 94,
        [InstallationMethod.METHOD_F]: 100,
        [InstallationMethod.METHOD_G]: 107,
        [InstallationMethod.METHOD_100]: 62,
        [InstallationMethod.METHOD_101]: 64,
        [InstallationMethod.METHOD_102]: 63,
        [InstallationMethod.METHOD_103]: 42.5,
      },
      mvAm: 2.8,
    },
    {
      size: 25,
      capacity: {
        [InstallationMethod.METHOD_A]: 82,
        [InstallationMethod.METHOD_B]: 99,
        [InstallationMethod.METHOD_C]: 110,
        [InstallationMethod.METHOD_D]: 121,
        [InstallationMethod.METHOD_E]: 121,
        [InstallationMethod.METHOD_F]: 135,
        [InstallationMethod.METHOD_G]: 146,
        [InstallationMethod.METHOD_100]: 80,
        [InstallationMethod.METHOD_101]: 82,
        [InstallationMethod.METHOD_102]: 81,
        [InstallationMethod.METHOD_103]: 55,
      },
      mvAm: 1.8,
    },
    {
      size: 35,
      capacity: {
        [InstallationMethod.METHOD_A]: 100,
        [InstallationMethod.METHOD_B]: 121,
        [InstallationMethod.METHOD_C]: 135,
        [InstallationMethod.METHOD_D]: 150,
        [InstallationMethod.METHOD_E]: 150,
        [InstallationMethod.METHOD_F]: 165,
        [InstallationMethod.METHOD_G]: 181,
        [InstallationMethod.METHOD_100]: 98,
        [InstallationMethod.METHOD_101]: 100,
        [InstallationMethod.METHOD_102]: 99,
        [InstallationMethod.METHOD_103]: 67,
      },
      mvAm: 1.3,
    },
    {
      size: 50,
      capacity: {
        [InstallationMethod.METHOD_A]: 119,
        [InstallationMethod.METHOD_B]: 145,
        [InstallationMethod.METHOD_C]: 163,
        [InstallationMethod.METHOD_D]: 181,
        [InstallationMethod.METHOD_E]: 181,
        [InstallationMethod.METHOD_F]: 201,
        [InstallationMethod.METHOD_G]: 219,
        [InstallationMethod.METHOD_100]: 115,
        [InstallationMethod.METHOD_101]: 119,
        [InstallationMethod.METHOD_102]: 118,
        [InstallationMethod.METHOD_103]: 80,
      },
      mvAm: 0.93,
    },
    {
      size: 70,
      capacity: {
        [InstallationMethod.METHOD_A]: 149,
        [InstallationMethod.METHOD_B]: 183,
        [InstallationMethod.METHOD_C]: 207,
        [InstallationMethod.METHOD_D]: 230,
        [InstallationMethod.METHOD_E]: 230,
        [InstallationMethod.METHOD_F]: 255,
        [InstallationMethod.METHOD_G]: 279,
        [InstallationMethod.METHOD_100]: 145,
        [InstallationMethod.METHOD_101]: 149,
        [InstallationMethod.METHOD_102]: 148,
        [InstallationMethod.METHOD_103]: 100,
      },
      mvAm: 0.67,
    },
    {
      size: 95,
      capacity: {
        [InstallationMethod.METHOD_A]: 179,
        [InstallationMethod.METHOD_B]: 220,
        [InstallationMethod.METHOD_C]: 251,
        [InstallationMethod.METHOD_D]: 280,
        [InstallationMethod.METHOD_E]: 280,
        [InstallationMethod.METHOD_F]: 310,
        [InstallationMethod.METHOD_G]: 340,
        [InstallationMethod.METHOD_100]: 175,
        [InstallationMethod.METHOD_101]: 179,
        [InstallationMethod.METHOD_102]: 178,
        [InstallationMethod.METHOD_103]: 120,
      },
      mvAm: 0.49,
    },
    {
      size: 120,
      capacity: {
        [InstallationMethod.METHOD_A]: 206,
        [InstallationMethod.METHOD_B]: 255,
        [InstallationMethod.METHOD_C]: 291,
        [InstallationMethod.METHOD_D]: 325,
        [InstallationMethod.METHOD_E]: 325,
        [InstallationMethod.METHOD_F]: 360,
        [InstallationMethod.METHOD_G]: 395,
        [InstallationMethod.METHOD_100]: 200,
        [InstallationMethod.METHOD_101]: 206,
        [InstallationMethod.METHOD_102]: 205,
        [InstallationMethod.METHOD_103]: 140,
      },
      mvAm: 0.39,
    },
    {
      size: 150,
      capacity: {
        [InstallationMethod.METHOD_A]: 235,
        [InstallationMethod.METHOD_B]: 290,
        [InstallationMethod.METHOD_C]: 334,
        [InstallationMethod.METHOD_D]: 373,
        [InstallationMethod.METHOD_E]: 373,
        [InstallationMethod.METHOD_F]: 410,
        [InstallationMethod.METHOD_G]: 450,
        [InstallationMethod.METHOD_100]: 230,
        [InstallationMethod.METHOD_101]: 235,
        [InstallationMethod.METHOD_102]: 234,
        [InstallationMethod.METHOD_103]: 160,
      },
      mvAm: 0.32,
    },
    {
      size: 185,
      capacity: {
        [InstallationMethod.METHOD_A]: 268,
        [InstallationMethod.METHOD_B]: 330,
        [InstallationMethod.METHOD_C]: 384,
        [InstallationMethod.METHOD_D]: 420,
        [InstallationMethod.METHOD_E]: 420,
        [InstallationMethod.METHOD_F]: 470,
        [InstallationMethod.METHOD_G]: 515,
        [InstallationMethod.METHOD_100]: 260,
        [InstallationMethod.METHOD_101]: 268,
        [InstallationMethod.METHOD_102]: 267,
        [InstallationMethod.METHOD_103]: 185,
      },
      mvAm: 0.26,
    },
    {
      size: 240,
      capacity: {
        [InstallationMethod.METHOD_A]: 315,
        [InstallationMethod.METHOD_B]: 390,
        [InstallationMethod.METHOD_C]: 458,
        [InstallationMethod.METHOD_D]: 500,
        [InstallationMethod.METHOD_E]: 500,
        [InstallationMethod.METHOD_F]: 560,
        [InstallationMethod.METHOD_G]: 615,
        [InstallationMethod.METHOD_100]: 305,
        [InstallationMethod.METHOD_101]: 315,
        [InstallationMethod.METHOD_102]: 314,
        [InstallationMethod.METHOD_103]: 215,
      },
      mvAm: 0.20,
    },
    {
      size: 300,
      capacity: {
        [InstallationMethod.METHOD_A]: 360,
        [InstallationMethod.METHOD_B]: 445,
        [InstallationMethod.METHOD_C]: 526,
        [InstallationMethod.METHOD_D]: 575,
        [InstallationMethod.METHOD_E]: 575,
        [InstallationMethod.METHOD_F]: 645,
        [InstallationMethod.METHOD_G]: 705,
        [InstallationMethod.METHOD_100]: 350,
        [InstallationMethod.METHOD_101]: 360,
        [InstallationMethod.METHOD_102]: 359,
        [InstallationMethod.METHOD_103]: 250,
      },
      mvAm: 0.16,
    },
    {
      size: 400,
      capacity: {
        [InstallationMethod.METHOD_A]: 430,
        [InstallationMethod.METHOD_B]: 530,
        [InstallationMethod.METHOD_C]: 630,
        [InstallationMethod.METHOD_D]: 685,
        [InstallationMethod.METHOD_E]: 685,
        [InstallationMethod.METHOD_F]: 770,
        [InstallationMethod.METHOD_G]: 840,
        [InstallationMethod.METHOD_100]: 415,
        [InstallationMethod.METHOD_101]: 430,
        [InstallationMethod.METHOD_102]: 429,
        [InstallationMethod.METHOD_103]: 295,
      },
      mvAm: 0.12,
    },
  ],
  [CableType.XLPE_SWA]: [
    {
      size: 1.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 19,
        [InstallationMethod.METHOD_B]: 22,
        [InstallationMethod.METHOD_C]: 25,
        [InstallationMethod.METHOD_D]: 26,
        [InstallationMethod.METHOD_E]: 26,
        [InstallationMethod.METHOD_F]: 27,
        [InstallationMethod.METHOD_G]: 28,
        [InstallationMethod.METHOD_100]: 20,
        [InstallationMethod.METHOD_101]: 19,
        [InstallationMethod.METHOD_102]: 20,
        [InstallationMethod.METHOD_103]: 13,
      },
      mvAm: 31,
    },
    {
      size: 2.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 25,
        [InstallationMethod.METHOD_B]: 29,
        [InstallationMethod.METHOD_C]: 33,
        [InstallationMethod.METHOD_D]: 35,
        [InstallationMethod.METHOD_E]: 35,
        [InstallationMethod.METHOD_F]: 36,
        [InstallationMethod.METHOD_G]: 38,
        [InstallationMethod.METHOD_100]: 26,
        [InstallationMethod.METHOD_101]: 25,
        [InstallationMethod.METHOD_102]: 26,
        [InstallationMethod.METHOD_103]: 17,
      },
      mvAm: 19,
    },
    {
      size: 4,
      capacity: {
        [InstallationMethod.METHOD_A]: 34,
        [InstallationMethod.METHOD_B]: 40,
        [InstallationMethod.METHOD_C]: 45,
        [InstallationMethod.METHOD_D]: 47,
        [InstallationMethod.METHOD_E]: 47,
        [InstallationMethod.METHOD_F]: 49,
        [InstallationMethod.METHOD_G]: 52,
        [InstallationMethod.METHOD_100]: 35,
        [InstallationMethod.METHOD_101]: 34,
        [InstallationMethod.METHOD_102]: 35,
        [InstallationMethod.METHOD_103]: 23,
      },
      mvAm: 12,
    },
    {
      size: 6,
      capacity: {
        [InstallationMethod.METHOD_A]: 43,
        [InstallationMethod.METHOD_B]: 51,
        [InstallationMethod.METHOD_C]: 58,
        [InstallationMethod.METHOD_D]: 61,
        [InstallationMethod.METHOD_E]: 61,
        [InstallationMethod.METHOD_F]: 63,
        [InstallationMethod.METHOD_G]: 67,
        [InstallationMethod.METHOD_100]: 45,
        [InstallationMethod.METHOD_101]: 43,
        [InstallationMethod.METHOD_102]: 45,
        [InstallationMethod.METHOD_103]: 30,
      },
      mvAm: 7.9,
    },
    {
      size: 10,
      capacity: {
        [InstallationMethod.METHOD_A]: 60,
        [InstallationMethod.METHOD_B]: 71,
        [InstallationMethod.METHOD_C]: 80,
        [InstallationMethod.METHOD_D]: 84,
        [InstallationMethod.METHOD_E]: 84,
        [InstallationMethod.METHOD_F]: 87,
        [InstallationMethod.METHOD_G]: 93,
        [InstallationMethod.METHOD_100]: 62,
        [InstallationMethod.METHOD_101]: 60,
        [InstallationMethod.METHOD_102]: 62,
        [InstallationMethod.METHOD_103]: 41,
      },
      mvAm: 4.7,
    },
    {
      size: 16,
      capacity: {
        [InstallationMethod.METHOD_A]: 80,
        [InstallationMethod.METHOD_B]: 94,
        [InstallationMethod.METHOD_C]: 107,
        [InstallationMethod.METHOD_D]: 113,
        [InstallationMethod.METHOD_E]: 113,
        [InstallationMethod.METHOD_F]: 117,
        [InstallationMethod.METHOD_G]: 125,
        [InstallationMethod.METHOD_100]: 83,
        [InstallationMethod.METHOD_101]: 80,
        [InstallationMethod.METHOD_102]: 83,
        [InstallationMethod.METHOD_103]: 55,
      },
      mvAm: 2.9,
    },
    {
      size: 25,
      capacity: {
        [InstallationMethod.METHOD_A]: 98,
        [InstallationMethod.METHOD_B]: 115,
        [InstallationMethod.METHOD_C]: 131,
        [InstallationMethod.METHOD_D]: 138,
        [InstallationMethod.METHOD_E]: 138,
        [InstallationMethod.METHOD_F]: 143,
        [InstallationMethod.METHOD_G]: 153,
        [InstallationMethod.METHOD_100]: 102,
        [InstallationMethod.METHOD_101]: 98,
        [InstallationMethod.METHOD_102]: 102,
        [InstallationMethod.METHOD_103]: 68,
      },
      mvAm: 1.9,
    },
    {
      size: 35,
      capacity: {
        [InstallationMethod.METHOD_A]: 121,
        [InstallationMethod.METHOD_B]: 142,
        [InstallationMethod.METHOD_C]: 162,
        [InstallationMethod.METHOD_D]: 171,
        [InstallationMethod.METHOD_E]: 171,
        [InstallationMethod.METHOD_F]: 177,
        [InstallationMethod.METHOD_G]: 189,
        [InstallationMethod.METHOD_100]: 126,
        [InstallationMethod.METHOD_101]: 121,
        [InstallationMethod.METHOD_102]: 126,
        [InstallationMethod.METHOD_103]: 84,
      },
      mvAm: 1.35,
    },
    {
      size: 50,
      capacity: {
        [InstallationMethod.METHOD_A]: 147,
        [InstallationMethod.METHOD_B]: 173,
        [InstallationMethod.METHOD_C]: 197,
        [InstallationMethod.METHOD_D]: 208,
        [InstallationMethod.METHOD_E]: 208,
        [InstallationMethod.METHOD_F]: 215,
        [InstallationMethod.METHOD_G]: 230,
        [InstallationMethod.METHOD_100]: 153,
        [InstallationMethod.METHOD_101]: 147,
        [InstallationMethod.METHOD_102]: 153,
        [InstallationMethod.METHOD_103]: 102,
      },
      mvAm: 0.99,
    },
    {
      size: 70,
      capacity: {
        [InstallationMethod.METHOD_A]: 187,
        [InstallationMethod.METHOD_B]: 220,
        [InstallationMethod.METHOD_C]: 251,
        [InstallationMethod.METHOD_D]: 265,
        [InstallationMethod.METHOD_E]: 265,
        [InstallationMethod.METHOD_F]: 274,
        [InstallationMethod.METHOD_G]: 293,
        [InstallationMethod.METHOD_100]: 194,
        [InstallationMethod.METHOD_101]: 187,
        [InstallationMethod.METHOD_102]: 194,
        [InstallationMethod.METHOD_103]: 129,
      },
      mvAm: 0.71,
    },
    {
      size: 95,
      capacity: {
        [InstallationMethod.METHOD_A]: 227,
        [InstallationMethod.METHOD_B]: 267,
        [InstallationMethod.METHOD_C]: 304,
        [InstallationMethod.METHOD_D]: 321,
        [InstallationMethod.METHOD_E]: 321,
        [InstallationMethod.METHOD_F]: 332,
        [InstallationMethod.METHOD_G]: 355,
        [InstallationMethod.METHOD_100]: 236,
        [InstallationMethod.METHOD_101]: 227,
        [InstallationMethod.METHOD_102]: 236,
        [InstallationMethod.METHOD_103]: 157,
      },
      mvAm: 0.52,
    },
    {
      size: 120,
      capacity: {
        [InstallationMethod.METHOD_A]: 263,
        [InstallationMethod.METHOD_B]: 310,
        [InstallationMethod.METHOD_C]: 353,
        [InstallationMethod.METHOD_D]: 373,
        [InstallationMethod.METHOD_E]: 373,
        [InstallationMethod.METHOD_F]: 385,
        [InstallationMethod.METHOD_G]: 412,
        [InstallationMethod.METHOD_100]: 274,
        [InstallationMethod.METHOD_101]: 263,
        [InstallationMethod.METHOD_102]: 274,
        [InstallationMethod.METHOD_103]: 183,
      },
      mvAm: 0.42,
    },
    {
      size: 150,
      capacity: {
        [InstallationMethod.METHOD_A]: 300,
        [InstallationMethod.METHOD_B]: 350,
        [InstallationMethod.METHOD_C]: 400,
        [InstallationMethod.METHOD_D]: 420,
        [InstallationMethod.METHOD_E]: 420,
        [InstallationMethod.METHOD_F]: 440,
        [InstallationMethod.METHOD_G]: 470,
        [InstallationMethod.METHOD_100]: 310,
        [InstallationMethod.METHOD_101]: 300,
        [InstallationMethod.METHOD_102]: 310,
        [InstallationMethod.METHOD_103]: 205,
      },
      mvAm: 0.34,
    },
    {
      size: 185,
      capacity: {
        [InstallationMethod.METHOD_A]: 340,
        [InstallationMethod.METHOD_B]: 400,
        [InstallationMethod.METHOD_C]: 460,
        [InstallationMethod.METHOD_D]: 480,
        [InstallationMethod.METHOD_E]: 480,
        [InstallationMethod.METHOD_F]: 500,
        [InstallationMethod.METHOD_G]: 540,
        [InstallationMethod.METHOD_100]: 350,
        [InstallationMethod.METHOD_101]: 340,
        [InstallationMethod.METHOD_102]: 350,
        [InstallationMethod.METHOD_103]: 235,
      },
      mvAm: 0.28,
    },
    {
      size: 240,
      capacity: {
        [InstallationMethod.METHOD_A]: 400,
        [InstallationMethod.METHOD_B]: 470,
        [InstallationMethod.METHOD_C]: 540,
        [InstallationMethod.METHOD_D]: 560,
        [InstallationMethod.METHOD_E]: 560,
        [InstallationMethod.METHOD_F]: 590,
        [InstallationMethod.METHOD_G]: 630,
        [InstallationMethod.METHOD_100]: 410,
        [InstallationMethod.METHOD_101]: 400,
        [InstallationMethod.METHOD_102]: 410,
        [InstallationMethod.METHOD_103]: 275,
      },
      mvAm: 0.22,
    },
    {
      size: 300,
      capacity: {
        [InstallationMethod.METHOD_A]: 460,
        [InstallationMethod.METHOD_B]: 540,
        [InstallationMethod.METHOD_C]: 620,
        [InstallationMethod.METHOD_D]: 640,
        [InstallationMethod.METHOD_E]: 640,
        [InstallationMethod.METHOD_F]: 670,
        [InstallationMethod.METHOD_G]: 720,
        [InstallationMethod.METHOD_100]: 470,
        [InstallationMethod.METHOD_101]: 460,
        [InstallationMethod.METHOD_102]: 470,
        [InstallationMethod.METHOD_103]: 315,
      },
      mvAm: 0.18,
    },
    {
      size: 400,
      capacity: {
        [InstallationMethod.METHOD_A]: 540,
        [InstallationMethod.METHOD_B]: 630,
        [InstallationMethod.METHOD_C]: 730,
        [InstallationMethod.METHOD_D]: 750,
        [InstallationMethod.METHOD_E]: 750,
        [InstallationMethod.METHOD_F]: 790,
        [InstallationMethod.METHOD_G]: 850,
        [InstallationMethod.METHOD_100]: 550,
        [InstallationMethod.METHOD_101]: 540,
        [InstallationMethod.METHOD_102]: 550,
        [InstallationMethod.METHOD_103]: 370,
      },
      mvAm: 0.14,
    },
  ],
  [CableType.PVC_SINGLE]: [
    {
      size: 1.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 14.5,
        [InstallationMethod.METHOD_B]: 17.5,
        [InstallationMethod.METHOD_C]: 20,
        [InstallationMethod.METHOD_D]: 22,
        [InstallationMethod.METHOD_E]: 22,
        [InstallationMethod.METHOD_F]: 23,
        [InstallationMethod.METHOD_G]: 24,
        [InstallationMethod.METHOD_100]: 16,
        [InstallationMethod.METHOD_101]: 14.5,
        [InstallationMethod.METHOD_102]: 16,
        [InstallationMethod.METHOD_103]: 10,
      },
      mvAm: 29,
    },
    {
      size: 2.5,
      capacity: {
        [InstallationMethod.METHOD_A]: 20,
        [InstallationMethod.METHOD_B]: 24,
        [InstallationMethod.METHOD_C]: 28,
        [InstallationMethod.METHOD_D]: 30,
        [InstallationMethod.METHOD_E]: 30,
        [InstallationMethod.METHOD_F]: 31,
        [InstallationMethod.METHOD_G]: 33,
        [InstallationMethod.METHOD_100]: 21,
        [InstallationMethod.METHOD_101]: 20,
        [InstallationMethod.METHOD_102]: 21,
        [InstallationMethod.METHOD_103]: 13.5,
      },
      mvAm: 18,
    },
    {
      size: 4,
      capacity: {
        [InstallationMethod.METHOD_A]: 26,
        [InstallationMethod.METHOD_B]: 32,
        [InstallationMethod.METHOD_C]: 37,
        [InstallationMethod.METHOD_D]: 40,
        [InstallationMethod.METHOD_E]: 40,
        [InstallationMethod.METHOD_F]: 42,
        [InstallationMethod.METHOD_G]: 45,
        [InstallationMethod.METHOD_100]: 27,
        [InstallationMethod.METHOD_101]: 26,
        [InstallationMethod.METHOD_102]: 27,
        [InstallationMethod.METHOD_103]: 17.5,
      },
      mvAm: 11,
    },
    {
      size: 6,
      capacity: {
        [InstallationMethod.METHOD_A]: 34,
        [InstallationMethod.METHOD_B]: 41,
        [InstallationMethod.METHOD_C]: 48,
        [InstallationMethod.METHOD_D]: 51,
        [InstallationMethod.METHOD_E]: 52,
        [InstallationMethod.METHOD_F]: 54,
        [InstallationMethod.METHOD_G]: 58,
        [InstallationMethod.METHOD_100]: 34,
        [InstallationMethod.METHOD_101]: 34,
        [InstallationMethod.METHOD_102]: 35,
        [InstallationMethod.METHOD_103]: 23.5,
      },
      mvAm: 7.3,
    },
    {
      size: 10,
      capacity: {
        [InstallationMethod.METHOD_A]: 46,
        [InstallationMethod.METHOD_B]: 57,
        [InstallationMethod.METHOD_C]: 66,
        [InstallationMethod.METHOD_D]: 70,
        [InstallationMethod.METHOD_E]: 71,
        [InstallationMethod.METHOD_F]: 75,
        [InstallationMethod.METHOD_G]: 80,
        [InstallationMethod.METHOD_100]: 45,
        [InstallationMethod.METHOD_101]: 46,
        [InstallationMethod.METHOD_102]: 47,
        [InstallationMethod.METHOD_103]: 32,
      },
      mvAm: 4.4,
    },
    {
      size: 16,
      capacity: {
        [InstallationMethod.METHOD_A]: 61,
        [InstallationMethod.METHOD_B]: 76,
        [InstallationMethod.METHOD_C]: 88,
        [InstallationMethod.METHOD_D]: 94,
        [InstallationMethod.METHOD_E]: 94,
        [InstallationMethod.METHOD_F]: 100,
        [InstallationMethod.METHOD_G]: 107,
        [InstallationMethod.METHOD_100]: 62,
        [InstallationMethod.METHOD_101]: 61,
        [InstallationMethod.METHOD_102]: 63,
        [InstallationMethod.METHOD_103]: 42.5,
      },
      mvAm: 2.8,
    },
    {
      size: 25,
      capacity: {
        [InstallationMethod.METHOD_A]: 78,
        [InstallationMethod.METHOD_B]: 101,
        [InstallationMethod.METHOD_C]: 114,
        [InstallationMethod.METHOD_D]: 121,
        [InstallationMethod.METHOD_E]: 121,
        [InstallationMethod.METHOD_F]: 135,
        [InstallationMethod.METHOD_G]: 146,
        [InstallationMethod.METHOD_100]: 80,
        [InstallationMethod.METHOD_101]: 78,
        [InstallationMethod.METHOD_102]: 81,
        [InstallationMethod.METHOD_103]: 55,
      },
      mvAm: 1.8,
    },
    {
      size: 35,
      capacity: {
        [InstallationMethod.METHOD_A]: 97,
        [InstallationMethod.METHOD_B]: 126,
        [InstallationMethod.METHOD_C]: 141,
        [InstallationMethod.METHOD_D]: 150,
        [InstallationMethod.METHOD_E]: 150,
        [InstallationMethod.METHOD_F]: 165,
        [InstallationMethod.METHOD_G]: 181,
        [InstallationMethod.METHOD_100]: 98,
        [InstallationMethod.METHOD_101]: 97,
        [InstallationMethod.METHOD_102]: 99,
        [InstallationMethod.METHOD_103]: 67,
      },
      mvAm: 1.3,
    },
    {
      size: 50,
      capacity: {
        [InstallationMethod.METHOD_A]: 116,
        [InstallationMethod.METHOD_B]: 153,
        [InstallationMethod.METHOD_C]: 171,
        [InstallationMethod.METHOD_D]: 181,
        [InstallationMethod.METHOD_E]: 181,
        [InstallationMethod.METHOD_F]: 201,
        [InstallationMethod.METHOD_G]: 219,
        [InstallationMethod.METHOD_100]: 115,
        [InstallationMethod.METHOD_101]: 116,
        [InstallationMethod.METHOD_102]: 118,
        [InstallationMethod.METHOD_103]: 80,
      },
      mvAm: 0.93,
    },
    {
      size: 70,
      capacity: {
        [InstallationMethod.METHOD_A]: 146,
        [InstallationMethod.METHOD_B]: 196,
        [InstallationMethod.METHOD_C]: 216,
        [InstallationMethod.METHOD_D]: 230,
        [InstallationMethod.METHOD_E]: 230,
        [InstallationMethod.METHOD_F]: 255,
        [InstallationMethod.METHOD_G]: 279,
        [InstallationMethod.METHOD_100]: 145,
        [InstallationMethod.METHOD_101]: 146,
        [InstallationMethod.METHOD_102]: 148,
        [InstallationMethod.METHOD_103]: 100,
      },
      mvAm: 0.67,
    },
    {
      size: 95,
      capacity: {
        [InstallationMethod.METHOD_A]: 176,
        [InstallationMethod.METHOD_B]: 238,
        [InstallationMethod.METHOD_C]: 264,
        [InstallationMethod.METHOD_D]: 280,
        [InstallationMethod.METHOD_E]: 280,
        [InstallationMethod.METHOD_F]: 310,
        [InstallationMethod.METHOD_G]: 340,
        [InstallationMethod.METHOD_100]: 175,
        [InstallationMethod.METHOD_101]: 176,
        [InstallationMethod.METHOD_102]: 178,
        [InstallationMethod.METHOD_103]: 120,
      },
      mvAm: 0.49,
    },
    {
      size: 120,
      capacity: {
        [InstallationMethod.METHOD_A]: 203,
        [InstallationMethod.METHOD_B]: 276,
        [InstallationMethod.METHOD_C]: 305,
        [InstallationMethod.METHOD_D]: 325,
        [InstallationMethod.METHOD_E]: 325,
        [InstallationMethod.METHOD_F]: 360,
        [InstallationMethod.METHOD_G]: 395,
        [InstallationMethod.METHOD_100]: 200,
        [InstallationMethod.METHOD_101]: 203,
        [InstallationMethod.METHOD_102]: 205,
        [InstallationMethod.METHOD_103]: 140,
      },
      mvAm: 0.39,
    },
    {
      size: 150,
      capacity: {
        [InstallationMethod.METHOD_A]: 232,
        [InstallationMethod.METHOD_B]: 318,
        [InstallationMethod.METHOD_C]: 351,
        [InstallationMethod.METHOD_D]: 375,
        [InstallationMethod.METHOD_E]: 375,
        [InstallationMethod.METHOD_F]: 415,
        [InstallationMethod.METHOD_G]: 455,
        [InstallationMethod.METHOD_100]: 230,
        [InstallationMethod.METHOD_101]: 232,
        [InstallationMethod.METHOD_102]: 235,
        [InstallationMethod.METHOD_103]: 160,
      },
      mvAm: 0.32,
    },
    {
      size: 185,
      capacity: {
        [InstallationMethod.METHOD_A]: 265,
        [InstallationMethod.METHOD_B]: 362,
        [InstallationMethod.METHOD_C]: 400,
        [InstallationMethod.METHOD_D]: 425,
        [InstallationMethod.METHOD_E]: 425,
        [InstallationMethod.METHOD_F]: 475,
        [InstallationMethod.METHOD_G]: 520,
        [InstallationMethod.METHOD_100]: 260,
        [InstallationMethod.METHOD_101]: 265,
        [InstallationMethod.METHOD_102]: 268,
        [InstallationMethod.METHOD_103]: 185,
      },
      mvAm: 0.26,
    },
    {
      size: 240,
      capacity: {
        [InstallationMethod.METHOD_A]: 311,
        [InstallationMethod.METHOD_B]: 424,
        [InstallationMethod.METHOD_C]: 470,
        [InstallationMethod.METHOD_D]: 500,
        [InstallationMethod.METHOD_E]: 500,
        [InstallationMethod.METHOD_F]: 560,
        [InstallationMethod.METHOD_G]: 615,
        [InstallationMethod.METHOD_100]: 305,
        [InstallationMethod.METHOD_101]: 311,
        [InstallationMethod.METHOD_102]: 315,
        [InstallationMethod.METHOD_103]: 215,
      },
      mvAm: 0.20,
    },
    {
      size: 300,
      capacity: {
        [InstallationMethod.METHOD_A]: 358,
        [InstallationMethod.METHOD_B]: 488,
        [InstallationMethod.METHOD_C]: 540,
        [InstallationMethod.METHOD_D]: 575,
        [InstallationMethod.METHOD_E]: 575,
        [InstallationMethod.METHOD_F]: 645,
        [InstallationMethod.METHOD_G]: 705,
        [InstallationMethod.METHOD_100]: 350,
        [InstallationMethod.METHOD_101]: 358,
        [InstallationMethod.METHOD_102]: 362,
        [InstallationMethod.METHOD_103]: 250,
      },
      mvAm: 0.16,
    },
    {
      size: 400,
      capacity: {
        [InstallationMethod.METHOD_A]: 425,
        [InstallationMethod.METHOD_B]: 580,
        [InstallationMethod.METHOD_C]: 640,
        [InstallationMethod.METHOD_D]: 685,
        [InstallationMethod.METHOD_E]: 685,
        [InstallationMethod.METHOD_F]: 770,
        [InstallationMethod.METHOD_G]: 840,
        [InstallationMethod.METHOD_100]: 415,
        [InstallationMethod.METHOD_101]: 425,
        [InstallationMethod.METHOD_102]: 430,
        [InstallationMethod.METHOD_103]: 295,
      },
      mvAm: 0.12,
    },
  ],
};

export const PROTECTIVE_DEVICES = [6, 10, 16, 20, 25, 32, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400];

export const VOLTAGES = {
  SINGLE_PHASE: 230,
  THREE_PHASE: 400,
};

export const AMBIENT_TEMP_FACTORS: Record<number, number> = {
  25: 1.03,
  30: 1.0,
  35: 0.94,
  40: 0.87,
  45: 0.79,
  50: 0.71,
};

export const GROUPING_FACTORS: Record<number, number> = {
  1: 1.0,
  2: 0.80,
  3: 0.70,
  4: 0.65,
  5: 0.60,
  6: 0.57,
  7: 0.54,
  8: 0.52,
  9: 0.50,
};

export const CABLE_CONFIGURATIONS = [
  { size: '1.0/1.0', label: '1.0mm² / 1.0mm²', resistance: 36.2 },
  { size: '1.5/1.0', label: '1.5mm² / 1.0mm²', resistance: 30.2 },
  { size: '2.5/1.5', label: '2.5mm² / 1.5mm²', resistance: 19.51 },
  { size: '4.0/1.5', label: '4.0mm² / 1.5mm²', resistance: 16.71 },
  { size: '6.0/2.5', label: '6.0mm² / 2.5mm²', resistance: 10.49 },
  { size: '10.0/4.0', label: '10.0mm² / 4.0mm²', resistance: 6.44 },
  { size: '16.0/6.0', label: '16.0mm² / 6.0mm²', resistance: 2.98 },
  { size: '25.0/10.0', label: '25.0mm² / 10.0mm²', resistance: 2.557 },
  { size: '35.0/16.0', label: '35.0mm² / 16.0mm²', resistance: 1.674 },
  { size: '50.0/25.0', label: '50.0mm² / 25.0mm²', resistance: 1.114 },
];

export const CABLE_RESISTANCE: Record<number, number> = {
  1.0: 18.1,
  1.5: 12.1,
  2.5: 7.41,
  4.0: 4.61,
  6.0: 3.08,
  10.0: 1.83,
  16.0: 1.15,
  25.0: 0.727,
  35.0: 0.524,
  50.0: 0.387,
  70.0: 0.268,
  95.0: 0.193,
  120.0: 0.153,
  150.0: 0.124,
  185.0: 0.0991,
  240.0: 0.0754,
  300.0: 0.0601,
  400.0: 0.0470,
};

// BS 7671:2018+A3:2024 Max Zs values (0.4s disconnection, 230V, Cmin=0.95)
export const DEVICE_LIMITS: Record<DeviceType, Record<number, number>> = {
  [DeviceType.MCB_B]: {
    6: 7.28,
    10: 4.37,
    16: 2.73,
    20: 2.19,
    25: 1.75,
    32: 1.37,
    40: 1.09,
    50: 0.87,
    63: 0.69,
    80: 0.55,
    100: 0.44,
    125: 0.35,
    160: 0.27,
    200: 0.22,
    250: 0.17,
    315: 0.14,
    400: 0.11,
  },
  [DeviceType.MCB_C]: {
    6: 3.64,
    10: 2.19,
    16: 1.37,
    20: 1.09,
    25: 0.87,
    32: 0.68,
    40: 0.55,
    50: 0.44,
    63: 0.35,
    80: 0.27,
    100: 0.22,
    125: 0.17,
    160: 0.14,
    200: 0.11,
    250: 0.09,
    315: 0.07,
    400: 0.05,
  },
  [DeviceType.MCB_D]: {
    6: 1.82,
    10: 1.09,
    16: 0.68,
    20: 0.55,
    25: 0.44,
    32: 0.34,
    40: 0.27,
    50: 0.22,
    63: 0.17,
    80: 0.14,
    100: 0.11,
    125: 0.09,
    160: 0.07,
    200: 0.05,
    250: 0.04,
    315: 0.03,
    400: 0.02,
  },
  [DeviceType.BS88_2]: {
    2: 15.3,
    4: 8.1,
    6: 5.11,
    10: 3.2,
    16: 1.92,
    20: 1.35,
    25: 1.04,
    32: 0.76,
    40: 0.56,
    50: 0.41,
    63: 0.30,
    80: 0.21,
    100: 0.16,
    125: 0.12,
    160: 0.09,
    200: 0.07,
    250: 0.05,
    315: 0.04,
    400: 0.03,
  },
  [DeviceType.BS88_2_5S]: {
    2: 15.3,
    4: 8.1,
    6: 13.5,
    10: 7.4,
    16: 4.1,
    20: 3.2,
    25: 2.3,
    32: 1.7,
    40: 1.3,
    50: 1.0,
    63: 0.82,
    80: 0.6,
    100: 0.46,
    125: 0.36,
    160: 0.28,
    200: 0.21,
    250: 0.16,
    315: 0.12,
    400: 0.09,
  },
  [DeviceType.BS88_3]: {
    5: 8.76,
    10: 3.94,
    16: 2.19,
    20: 1.53,
    25: 1.15,
    32: 0.87,
    45: 0.52,
    63: 0.35,
  },
  [DeviceType.BS3036]: {
    5: 7.66,
    15: 2.19,
    20: 1.44,
    30: 0.91,
    45: 0.51,
    60: 0.37,
  },
  [DeviceType.BS1361]: {
    5: 8.76,
    15: 2.73,
    20: 1.53,
    30: 0.96,
    45: 0.52,
    60: 0.35,
    80: 0.24,
    100: 0.18,
  },
};
